@extends('layouts.other')

@section('meta')
    <title>Terms and Conditions | Phone Friend</title>
    <meta name="description"
          content="Your use of a Phonefriend website and services and tools are governed by the following terms and conditions as applicable to the Phonefriend. Read more…"/>
@endsection

@section('content')

    <div class="site-content" tabindex="-1">
        <div class="container">

            <nav class="woocommerce-breadcrumb">
                <a href="/home">Home</a>
                <span class="delimiter"><i class="fa fa-angle-right"></i></span>
                Terms and Conditions
            </nav><!-- .woocommerce-breadcrumb -->


            <div id="primary" class="content-area">
                <main id="main" class="site-main">


                    <article id="post-2183" class="hentry">

                        <header class="entry-header">
                            <h1 class="entry-title">Terms and Conditions</h1>
                            <p class="entry-subtitle">This Agreement was last modified on 5 July 2019.</p>
                        </header><!-- .entry-header -->

                        <div class="entry-content">
                            <section class="section inner-bottom-xs">
                                <div>
                                    <div class="m_-6561140545157961077gmail-row">
                                        <div class="m_-6561140545157961077gmail-large-12 m_-6561140545157961077gmail-columns">
                                            <div class="m_-6561140545157961077gmail-dynamicHtmlContent">
                                                <p>This document is an electronic record in terms of Information
                                                    Technology Act, 2000 and rules there under as applicable and the
                                                    amended provisions pertaining to electronic records in various
                                                    statutes as amended by the Information Technology Act, 2000. This
                                                    electronic record is generated by a computer system and does not
                                                    require any physical or digital signatures.</p>
                                                <p>Your use of a Phonefriend website www.Phonefriend.com (hereinafter
                                                    referred to as "Phonefriend") and services and tools are governed by
                                                    the following terms and conditions as applicable to the&nbsp;Phonefriend.
                                                    If you transact on&nbsp;Phonefriend, you shall be subject to the
                                                    policies that are applicable to the website for such transaction. By
                                                    mere use of the website you shall be contracting with SOULERGY INDIA
                                                    SERVICES Pvt. Ltd., a company incorporated under Companies Act, 1956
                                                    with Corporate office at F-23<span style="font-family: inherit;">,Panch Mandir Road,Rudrapur, Uttrakhand India and these terms and conditions constitute your binding obligations.</span>
                                                </p>
                                                <p>For the purpose of these terms of use, wherever the context so
                                                    require &lsquo;You&rsquo; shall mean any natural or legal person who
                                                    has agreed to become a member of the Website by providing
                                                    Registration Data while registering on the Website as Registered
                                                    User using the computer systems of the Togofogo.</p>
                                                <p>When you use any of the services provided by the Phonefriend,
                                                    including but not limited to, (e.g., Customer Reviews), you will be
                                                    subject to the rules, guidelines, policies, terms, and conditions
                                                    applicable to such service, and they shall be deemed to be
                                                    incorporated into this Terms of Use and shall be considered as part
                                                    and parcel of this Terms of Use.&nbsp;Phonefriend&nbsp;reserves the
                                                    right, at its sole discretion, to change, modify, add or remove
                                                    portions of these Terms of Use, at any time. It is your
                                                    responsibility to check these Terms of Use periodically for changes.
                                                    Your continued use of the Site following the posting of changes will
                                                    mean that you accept and agree to the changes. As long as you comply
                                                    with these Terms of Use,&nbsp;Phonefriend&nbsp;grants you a
                                                    personal, non-exclusive, non-transferable, limited privilege to
                                                    enter and use the Site.</p>
                                                <p>ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR
                                                    AGREEMENT TO ALL THE TERMS AND CONDITIONS IN THIS AGREEMENT, SO
                                                    PLEASE READ THIS AGREEMENT CAREFULLY BEFORE PROCEEDING</p>
                                                <p><strong>Membership Eligibility</strong></p>
                                                <p>Use of the&nbsp;Phonefriend&nbsp;Website is available only to persons
                                                    who can form legally binding contracts under Indian Contract Act,
                                                    1872. Persons who are "incompetent to contract" within the meaning
                                                    of the Indian Contract Act, 1872 including minors, un-discharged
                                                    insolvents etc. are not eligible to use the&nbsp;Phonefriend&nbsp;Website.
                                                    If you are a minor i.e. under the age of 18 years, you shall not
                                                    register as a member of the&nbsp;Phonefriend&nbsp;and shall not
                                                    transact or use&nbsp;Phonefriend&nbsp;website. As a minor if you
                                                    wish to use or transact on&nbsp;Phonefriend, such use or transaction
                                                    may be made by your legal guardian or parents who have registered as
                                                    users of the&nbsp;Phonefriend.&nbsp;Phonefriendreserves the right to
                                                    terminate your membership and refuse to provide you with access to
                                                    the&nbsp;Phonefriend&nbsp;if it is brought to&nbsp;Phonefriend&rsquo;
                                                    s notice or if it is discovered that you are under the age of 18
                                                    years.</p>
                                                <p><strong>Your Account and Registration Obligations</strong></p>
                                                <p>If you use&nbsp;Phonefriend, you shall be responsible for maintaining
                                                    the confidentiality of your User ID and Password and you shall be
                                                    responsible for all activities that occur under your User ID and
                                                    Password. You agree that if you provide any information that is
                                                    untrue, inaccurate, not current or incomplete or&nbsp;Phonefriend&nbsp;has
                                                    reasonable grounds to suspect that such information is untrue,
                                                    inaccurate, not current or incomplete, or not in accordance with the
                                                    this Terms of Use,&nbsp;Phonefriend&nbsp;has the right to
                                                    indefinitely suspend or terminate or block access of your membership
                                                    with&nbsp;Phonefriend&nbsp;and refuse to provide you with access to
                                                    the Website.</p>
                                                <p><strong>Communications</strong></p>
                                                <p>When You use the Website or send emails or other data, information or
                                                    communication to&nbsp;Phonefriend, You agree and understand that You
                                                    are communicating with&nbsp;Phonefriend&nbsp;through electronic
                                                    records and You consent to receive communications via electronic
                                                    records from&nbsp;Phonefriend&nbsp;periodically and as and when
                                                    required.&nbsp;Phonefriend&nbsp;may communicate with You by email or
                                                    by such other mode of communication, electronic or otherwise.</p>
                                                <p><strong>Charges</strong></p>
                                                <p>Membership on the&nbsp;Phonefriend&nbsp;is free.&nbsp;Phonefriend&nbsp;does
                                                    not charge any fee for browsing and buying on the&nbsp;Phonefriend.
                                                    However&nbsp;Phonefriend&nbsp;reserves the right to charge fee and
                                                    change its policies from time to time. In particular,&nbsp;Phonefriend&nbsp;may
                                                    at its sole discretion introduce new services and modify some or all
                                                    of the existing services offered on the&nbsp;Phonefriend. In such an
                                                    event&nbsp;Phonefriend&nbsp;reserves, without notice to You, the
                                                    right to introduce fees for the new services offered or
                                                    amend/introduce fees for existing services, as the case may be.
                                                    Changes to the Fee and related policies shall automatically become
                                                    effective immediately once implemented on&nbsp;Phonefriend. Unless
                                                    otherwise stated, all fees shall be quoted in Indian Rupees. You
                                                    shall be solely responsible for compliance of all applicable laws
                                                    including those in India for making payments
                                                    to&nbsp;Phonefriend.</p><br>
                                                <b>Use of&nbsp;Phonefriend&nbsp;Website www.Phonefriend.com</b><br>
                                                <p>You agree, undertake and confirm that your use of&nbsp;Phonefriend&nbsp;shall
                                                    be strictly governed by the following binding principles:</p>
                                                <p>You shall not host, display, upload, modify, publish, transmit,
                                                    update or share any information:&nbsp;<br/>(a) belongs to another
                                                    person and to which You does not have any right to.<br/>(b) is
                                                    grossly harmful, harassing, blasphemous, defamatory, obscene,
                                                    pornographic, paedophilic, libellous, invasive of another's privacy,
                                                    hateful, or racially, ethnically objectionable, disparaging,
                                                    relating or encouraging money laundering or gambling, or otherwise
                                                    unlawful in any manner whatever; or unlawfully threatening or
                                                    unlawfully harassing including but not limited to "indecent
                                                    representation of women" within the meaning of the Indecent
                                                    Representation of Women (Prohibition) Act, 1986;<br/>(c) misleading
                                                    in any way.&nbsp;<br/>(d) is patently offensive to the online
                                                    community, such as sexually explicit content, or content that
                                                    promotes obscenity, paedophilia, racism, bigotry, hatred or physical
                                                    harm of any kind against any group or individual;&nbsp;<br/>(e)
                                                    harasses or advocates harassment of another person;<br/>(f) involves
                                                    the transmission of "junk mail," "chain letters," or unsolicited
                                                    mass mailing or "spamming";&nbsp;<br/>(g) promotes illegal
                                                    activities or conduct that is abusive, threatening, obscene,
                                                    defamatory or libellous;<br/>(h) infringes upon or violates any
                                                    third party's rights [(including, but not limited to, intellectual
                                                    property rights, rights of privacy (including without limitation
                                                    unauthorized disclosure of a person's name, email address, physical
                                                    address or phone number) or rights of publicity];<br/>(i) promotes
                                                    an illegal or unauthorized copy of another person's copyrighted work
                                                    (see "Copyright complaint" below for instructions on how to lodge a
                                                    complaint about uploaded copyrighted material), such as providing
                                                    pirated computer programs or links to them, providing information to
                                                    circumvent manufacture-installed copy-protect devices, or providing
                                                    pirated music or links to pirated music files;<br/>(j) contains
                                                    restricted or password-only access pages, or hidden pages or images
                                                    (those not linked to or from another accessible page);<br/>(l)
                                                    provides material that exploits people in a sexual, violent or
                                                    otherwise inappropriate manner or solicits personal information from
                                                    anyone;<br/>(m) provides instructional information about illegal
                                                    activities such as making or buying illegal weapons, violating
                                                    someone's privacy, or providing or creating computer viruses;<br/>(n)
                                                    contains video, photographs, or images of another person age 18 or
                                                    older without his or her express written consent and permission or
                                                    those of any minor (regardless of whether you have consent from the
                                                    minor or his or her legal guardian).<br/>(o) tries to gain
                                                    unauthorized access or exceeds the scope of authorized access (as
                                                    defined herein and in other applicable Codes of Conduct or End User
                                                    Access and License Agreements) to the Sites or to profiles, blogs,
                                                    communities, account information, bulletins, friend request, or
                                                    other areas of the Sites or solicits passwords or personal
                                                    identifying information for commercial or unlawful purposes from
                                                    other users;<br/>(p) engages in commercial activities and/or sales
                                                    without&nbsp;Phonefriend&rsquo; s prior written consent such as
                                                    contests, sweepstakes, barter, advertising and pyramid schemes, or
                                                    the buying or selling of "virtual" items related to the Sites.
                                                    Throughout this Terms of Use,&nbsp;Phonefriend&nbsp;"prior written
                                                    consent" means a communication coming from&nbsp;Phonefriend&nbsp;Legal
                                                    department, specifically in response to your request, and
                                                    specifically addressing the activity or conduct for which you seek
                                                    authorization;<br/>(q) solicits gambling or engages in any gambling
                                                    activity which&nbsp;Phonefriend, in its sole discretion, believes is
                                                    or could be construed as being illegal;<br/>(r) interferes with
                                                    another user's use and enjoyment of the&nbsp;Phonefriend&nbsp;Website
                                                    or any other individual's user and enjoyment of similar
                                                    services;<br/>(s) refers to any website or URL that, in the sole
                                                    discretion of&nbsp;Phonefriend, contains material that is
                                                    inappropriate for the&nbsp;Phonefriend&nbsp;Website or any other
                                                    Website, contains content that would be prohibited or violates the
                                                    letter or spirit of these Terms of Use.<br/>(t) harm minors in any
                                                    way;<br/>(u) infringes any patent, trademark, copyright or other
                                                    proprietary rights or third party&rsquo;s trade secrets or rights of
                                                    publicity or privacy or shall not be fraudulent or involve the sale
                                                    of counterfeit or stolen items;&nbsp;<br/>(v) violates any law for
                                                    the time being in force;<br/>(w) deceives or misleads the addressee/
                                                    users about the origin of such messages or communicates any
                                                    information which is grossly offensive or menacing in nature;<br/>(x)
                                                    impersonate another person;<br/>(y) contains software viruses or any
                                                    other computer code, files or programs designed to interrupt,
                                                    destroy or limit the functionality of any computer resource; or
                                                    contains any Trojan horses, worms, time bombs, cancelbots, Easter
                                                    eggs or other computer programming routines that may damage,
                                                    detrimentally interfere with, diminish value of, surreptitiously
                                                    intercept or expropriate any system, data or personal information;&nbsp;<br/>(z)
                                                    threatens the unity, integrity, defence, security or sovereignty of
                                                    India, friendly relations with foreign states, or public order or
                                                    causes incitement to the commission of any cognizable offence or
                                                    prevents investigation of any offence or is insulting any other
                                                    nation.<br/>(aa) shall not be false, inaccurate or misleading;&nbsp;<br/>(ab)
                                                    shall not, directly or indirectly, offer, attempt to offer, trade or
                                                    attempt to trade in any item, the dealing of which is prohibited or
                                                    restricted in any manner under the provisions of any applicable law,
                                                    rule, regulation or guideline for the time being in
                                                    force.&nbsp;<br/>(ac) shall not create liability for us or cause us
                                                    to lose (in whole or in part) the services of our ISPs or other
                                                    suppliers;</p>
                                                <p>You shall not use any &ldquo;deep-link&rdquo;, &ldquo;page-scrape&rdquo;,
                                                    &ldquo;robot&rdquo;, &ldquo;spider&rdquo; or other automatic device,
                                                    program, algorithm or methodology, or any similar or equivalent
                                                    manual process, to access, acquire, copy or monitor any portion of
                                                    the Website or any Content, or in any way reproduce or circumvent
                                                    the navigational structure or presentation of the Website or any
                                                    Content, to obtain or attempt to obtain any materials, documents or
                                                    information through any means not purposely made available through
                                                    the Website.&nbsp;Phonefriend&nbsp;reserves the right to bar any
                                                    such activity.</p>
                                                <p>You shall not attempt to gain unauthorized access to any portion or
                                                    feature of&nbsp;Phonefriend&nbsp;website, or any other systems or
                                                    networks connected to&nbsp;Phonefriend&nbsp;Website or to any&nbsp;Phonefriend&rsquo;
                                                    s server, computer, network, or to any of the services offered on or
                                                    through&nbsp;Phonefriend&nbsp;Website, by hacking, password &ldquo;mining&rdquo;
                                                    or any other illegitimate means.</p>
                                                <p>You shall not probe, scan or test the vulnerability of&nbsp;Phonefriend&nbsp;website
                                                    or any network connected to&nbsp;Phonefriend&nbsp;website nor breach
                                                    the security or authentication measures on&nbsp;Phonefriend&nbsp;website
                                                    or any network connected to&nbsp;Phonefriend&nbsp;Website. You may
                                                    not reverse look-up, trace or seek to trace any information on any
                                                    other user of or visitor to&nbsp;Phonefriend&nbsp;Website, or any
                                                    other customer of&nbsp;Phonefriend, including any&nbsp;Phonefriend&nbsp;account
                                                    not owned by you, to its source, or exploit&nbsp;Phonefriend&nbsp;Website
                                                    or any service or information made available or offered by or
                                                    through&nbsp;Phonefriend&nbsp;Website, in any way where the purpose
                                                    is to reveal any information, including but not limited to personal
                                                    identification or information, other than your own information, as
                                                    provided for by&nbsp;Phonefriend&nbsp;Website.</p>
                                                <p>You agree that you will not take any action that imposes an
                                                    unreasonable or disproportionately large load on the infrastructure
                                                    of&nbsp;Phonefriend&nbsp;Website or&nbsp;Phonefriend&rsquo; s
                                                    systems or networks, or any systems or networks connected to the&nbsp;Phonefriend.</p>
                                                <p>You agree not to use any device, software or routine to interfere or
                                                    attempt to interfere with the proper working of the Website or any
                                                    transaction being conducted on the Website, or with any other person&rsquo;s
                                                    use of the Website.</p>
                                                <p>You may not forge headers or otherwise manipulate identifiers in
                                                    order to disguise the origin of any message or transmittal you send
                                                    to&nbsp;Phonefriend&nbsp;on or through the Website or any service
                                                    offered on or through the Website. You may not pretend that you are,
                                                    or that you represent, someone else, or impersonate any other
                                                    individual or entity.</p>
                                                <p>You may not use the Website or any Content for any purpose that is
                                                    unlawful or prohibited by these Terms of Use, or to solicit the
                                                    performance of any illegal activity or other activity which
                                                    infringes the rights of&nbsp;Phonefriend&nbsp;or others.</p>
                                                <p>Solely to enable&nbsp;Phonefriend&nbsp;to use the information you
                                                    supply us with, so that we are not violating any rights you might
                                                    have in Your Information, you agree to grant us a non-exclusive,
                                                    worldwide, perpetual, irrevocable, royalty-free, sub-licensable
                                                    (through multiple tiers) right to exercise the copyright, publicity,
                                                    database rights or any other rights you have in Your Information, in
                                                    any media now known or not currently known, with respect to Your
                                                    Information.&nbsp;Phonefriend&nbsp;will only use Your Information in
                                                    accordance with the terms of use and&nbsp;Phonefriend's&nbsp;Privacy
                                                    Policy.</p>
                                                <p>From time to time, you shall be responsible for providing information
                                                    relating to the items or services proposed to be sold by you. In
                                                    this connection, you undertake that all such information shall be
                                                    accurate in all respects. You shall not exaggerate or over emphasize
                                                    the attributes of such items or services so as to mislead other
                                                    Users in any manner.</p>
                                                <p>You shall not engage in advertising to, or solicitation of, other
                                                    users of&nbsp;Phonefriend&nbsp;to buy or sell any products or
                                                    services, including, but not limited to, products or services
                                                    related being displayed on&nbsp;Phonefriend&nbsp;or related to&nbsp;Phonefriend.
                                                    You may not transmit any chain letters or unsolicited commercial or
                                                    junk email to other users via&nbsp;Phonefriend. It shall be a
                                                    violation of these Terms of Use to use any information obtained from&nbsp;Phonefriend&nbsp;in
                                                    order to harass, abuse, or harm another person, or in order to
                                                    contact, advertise to, solicit, or sell to another person outside of
                                                    the&nbsp;Phonefriend&nbsp;without&nbsp;Phonefriend&rsquo; s prior
                                                    explicit consent. In order to protect our users from such
                                                    advertising or solicitation,&nbsp;Phonefriend&nbsp;reserves the
                                                    right to restrict the number of messages or emails which a user may
                                                    send to other users in any 24-hour period which&nbsp;Phonefriend&nbsp;deems
                                                    appropriate in its sole discretion.12. You understand that&nbsp;Phonefriend&nbsp;has
                                                    the right at all times to disclose any information (including the
                                                    identity of the persons providing information or materials on the&nbsp;Phonefriend&nbsp;Website)
                                                    as necessary to satisfy any law, regulation or valid governmental
                                                    request. This may include, without limitation, disclosure of the
                                                    information in connection with investigation of alleged illegal
                                                    activity or solicitation of illegal activity.</p>
                                                <br>
                                                <hr>
                                                <br>
                                                <li class="menu-box"><a href="{{route('footer.return')}}"
                                                                        style="font-weight: bold">Returns/Exchange</a>
                                                    <i class="fa fa-chevron-right" style="
    float: right;
"></i></li>
                                                <li class="menu-box"><a href="{{route('footer.terms')}}"
                                                                        style="font-weight: bold">Terms and
                                                        Conditions</a><i class="fa fa-chevron-right" style="
    float: right;
"></i></li>
                                                <li class="menu-box"><a href="{{route('footer.shipping')}}"
                                                                        style="font-weight: bold">Shipping Policy</a><i
                                                            class="fa fa-chevron-right" style="
    float: right;
"></i></li>
                                                <li class="menu-box"><a href="{{route('footer.cancellation')}}"
                                                                        style="font-weight: bold">Cancellation
                                                        Policy</a><i class="fa fa-chevron-right" style="
    float: right;
"></i></li>

                                            </div>
                                        </div>
                                    </div>
                                    <div class="yj6qo">&nbsp;</div>
                                </div>
                            </section><!-- .section -->


                        </div><!-- .entry-content -->

                    </article><!-- #post-## -->

                </main><!-- #main -->
            </div><!-- #primary -->


        </div><!-- .col-full -->
    </div><!-- #content -->





@endsection




